### PR TITLE
Christopher Hunt さんの "リアクティブ・マイクロサービス" の tag変更

### PR DESCRIPTION
**Pull request by xuwei-k**
slackで @eed3si9n さん経由で頼まれたので、これでいい(ある意味本人というかtypesafeとしての意向？)のはず

### CODE REVIEW

**Comment by xuwei-k** [comment]
あ、microserviceじゃなく、他のすでにあるやつ microservices で複数形になってる。そっちにそろえるか

**Comment by xuwei-k** [comment]
https://github.com/scalajp/2016.scalamatsuri.org/commit/270e573437c88a015b3bc3

**Comment by eed3si9n** [comment]
@huntc Your talk was originally tagged by one of the staff as "architecture,akka,play".
I asked them to switch it to "microservices,akka,reactive" I hope you don't mind :)

**Comment by huntc** [comment]
Ah, it actually applies to both play and Akka though. The examples I had were using both. :-)

**Comment by eed3si9n** [comment]
Right. But you can have only three tags. I figured you'd want Reactive and
Microservices.

**Comment by huntc** [comment]
OK, cool. Thanks.

**Pull request merged**
